[versions]
ben-manes-versions = "0.48.0"
kotest = "5.6.2"
kotlin = "1.9.10"
kotlinter = "3.16.0"
version-catalog-update = "0.8.1"

[libraries]
kotest = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

[plugins]
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = 'ben-manes-versions' }
kotiln-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }